### ISSUE TITLE
非Rubyアプリケーションのレポジトリで `ruby/setup-ruby` が失敗してしまう

### ISSUE THREAD

**Issue by ohbarye** [smartbank-inc/release-pr-workflow#12]
## 事象

非Rubyアプリケーションのレポジトリで `ruby/setup-ruby` が失敗してしまいます。

📝 エラーログ

```
Error: Error: input ruby-version needs to be specified if no .ruby-version or .tool-versions file exists
    at parseRubyEngineAndVersion (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:609[15](https://github.com/xxxxxxxx/xxxxxxxx/runs/6073631848?check_suite_focus=true#step:7:15):13)
    at setupRuby (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:60853:35)
    at run (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:60835:11)
    at /home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:60996:40
    at /home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:60998:3
    at Object.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:61001:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```

## 再現手順

`.ruby-version`が無いレポジトリでこのworkflowを実行する。

## 期待する挙動

リリースPRが作成される。

## 実際の挙動

リリースPRが作成されず、`ruby/setup-ruby` のステップで失敗する。

## エラーログ

```
Error: Error: input ruby-version needs to be specified if no .ruby-version or .tool-versions file exists
    at parseRubyEngineAndVersion (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:609[15](https://github.com/smartbank-inc/b43-aml-worker/runs/6073631848?check_suite_focus=true#step:7:15):13)
    at setupRuby (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:60853:35)
    at run (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:60835:11)
    at /home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:60996:40
    at /home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:60998:3
    at Object.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:61001:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```

**Comment by ohbarye** [comment]
## 原因

https://github.com/smartbank-inc/release-pr-workflow/pull/10 の修正にて`ruby-version`指定を外したのが原因。

`ruby/setup-ruby`は以下のいずれかでなければ失敗する
- `ruby-version`オプションから任意のRubyバージョンを渡す
- `.ruby-version`ファイルがレポジトリに存在する
- `.tool-versions`ファイルがレポジトリに存在する

refs https://github.com/ruby/setup-ruby/blob/b37f0a38ea6b76137ef9e37492d1b1882a594e4a/index.js#L97-L106

## 修正案

workflowを以下の挙動にする。

- レポジトリに`.ruby-version`ファイルがあればそれを使う
- なければ`3.1.2`を直接指定する
    - このRubyバージョンは git-pr-release CLI が動くバージョンであればなんでもよい。そのため現時点での最新を指定しておく
    - 新しいRubyがリリースされたら任意のタイミングで更新する
